"""
umachine.py is a mock/fake implementation of the MicroPython 'umachine' module for use by the CPython3 tests.
"""


def soft_reset():
    pass


def unique_id():
    return b"012345678"


def rng():
    """ rng returns a 30-bit random number that is generated by the software. """
    raise NotImplementedError("TODO Implement me!")
